excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://mojodemon.github.io
title: Mojodemon
tagline: bailwire and comb
description: Mojo Demon
The language of blues music
paginate: 10
