excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://mojodemon.github.io
title: mojodemon
tagline: bailwire and comb
description: Mojo Demon are Ady Davey + Shakin' Lips, performing the blues UK side of the pond. 
paginate: 10